channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - h5py
    - rdkit

    - sphinx=1.8
    - sphinx_rtd_theme
    - sphinx-autodoc-typehints

    - pyyaml=5.1
    - numpy
    - scipy
    - pandas
    - pymongo

    - pip:
        - schema
        - plams@git+https://github.com/SCM-NV/PLAMS@master
        - qmflows@git+https://github.com/SCM-NV/qmflows@master
        - data-CAT@git+https://github.com/nlesc-nano/data-CAT@master
        - nano-CAT@git+https://github.com/nlesc-nano/nano-CAT@master
