path: /Users/basvanbeek/Documents/CdSe/Week_5

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - CO
    - CCO
    - CCCO
    # - FragranceDB2.txt

optional:
    database:
        dirname: database
        read: True
        write: False
        overwrite: False
        mol_format: [pdb]
        mongodb: False

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        optimize: True
        split: True
        cosmo-rs: True

    qd:
        dirname: QD
        optimize: True
#        dissociate:
#            keep_files: False
#            core_atom: Cd
#            lig_count: 2
#            core_index: [67, 68, 69, 79, 80, 81]
