path: /Users/basvanbeek/Documents/CdSe/Week_5

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - CO
    - CCO
    # - FragranceDB2.txt

optional:
    database:
        dirname: database
        read: True
        write: True
        overwrite: False
        mol_format: [pdb]
        mongodb:
            username: bob  # An optional username
            password: my_fancy_password  # An optional password
            host: localhost
            port: 27017

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        optimize: True
        split: True
        cosmo-rs: False

    qd:
        dirname: QD
        optimize: False
        dissociate: False
