path: None

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - OC

optional:
    database:
        dirname: database
        read: True
        write: True
        overwrite: True
        mol_format: [xyz, pdb]
        mongodb: False

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        functional_groups: None
        optimize: True
        split: True
        cosmo-rs: True

    qd:
        dirname: QD
        optimize: True
        activation_strain: False
        dissociate: False
