path: /path/to/my/stuff

input_qd:
    - Cd68Se55_ethoxide.xyz:
        ligand_smiles: '[O-]CC'
        ligand_anchor: '[O-]'

optional:
    database:
        dirname: database
        read: True
        write: True
        overwrite: False
        mol_format: [pdb]
        mongodb: False

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        optimize: True
        split: True
        functional_groups: 'O(C=O)[H]'
        cosmo-rs: False

    qd:
        dirname: QD
        construct_qd: True
        optimize: False
        bulkiness: False
        activation_strain: False
