path: /Users/bvanbeek/Documents/CdSe/Week_5

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - CO
    # - FragranceDB2.txt

optional:
    database:
        dirname: database
        read: True
        write: True
        overwrite: False
        mol_format: [pdb]
        mongodb: False

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        optimize: True
        split: True
        cosmo-rs: True

    qd:
        dirname: QD
        optimize: False
        dissociate: False
