path: None

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - OC(C)=O
    - OC(CC)=O
    - OC(CCC)=O
    - OC(CCCC)=O

optional:
    dir_names: [core, ligand, QD, database]

    database:
        read: True
        write: True
        overwrite: False
        mol_format: [pdb, xyz]
        database_format: [xlsx, json]
        mongodb: False

    core:
        dummy: Cl

    ligand:
        optimize: True
        split: True
        cosmo-rs: False

    qd:
        optimize: False
        activation_strain: False
        dissociate: False
